name: Python package

on:
  push:
    branches:
      - master
  schedule:
    - cron: 00 00 * * *

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install chrome driver
        run: |
          sudo apt-get install wget
          sudo apt-get install unzip
          LATEST=$(google-chrome --product-version)
          echo $LATEST
          base_url="http://chromedriver.storage.googleapis.com/LATEST_RELEASE_"
          url=$base_url${LATEST%%.*}
          result=$(curl $url)
          echo $result
          sudo wget "https://chromedriver.storage.googleapis.com/$result/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          chmod +x chromedriver 
          sudo mv chromedriver /usr/bin/
          
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requeirments.txt
      - name: execute py script
        env:
          JUEJIN_USERNAME: ${{ secrets.JUEJIN_USERNAME }}
          JUEJIN_PASSWORD: ${{ secrets.JUEJIN_PASSWORD }}
          JUEJIN_NICKNAME: ${{ secrets.JUEJIN_NICKNAME }}
          MAIL_ADDRESS: ${{ secrets.MAIL_ADDRESS }}
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
          MAIL_USER: ${{ secrets.MAIL_USER }}
          SWITCH: ${{ secrets.SWITCH }}
          PUBLISH_SWITCH: ${{ secrets.PUBLISH_SWITCH }}

        run: |
          python main.py
